import {test} from 'node:test';
import assert from 'node:assert/strict';
import {initialFormulaState,submitFormula,reviewFormula} from '../src/dye-formula-model.ts';
const modified=state=>({...structuredClone(state.approved),bath:10});
test('配方修改提交后保留原配方，工段长通过才生效',()=>{const initial=initialFormulaState();const submitted=submitFormula(initial,modified(initial),'修正浴比',0);assert.equal(submitted.approved.bath,9);assert.equal(submitted.changes[0].status,'待工段长审核');const approved=reviewFormula(submitted,submitted.changes[0].id,true,'张工','同意');assert.equal(approved.approved.bath,10);assert.equal(approved.version,1);assert.equal(approved.changes[0].before.bath,9);assert.equal(approved.changes[0].reviewer,'张工');});
test('退回保留原配方，可重新修改提交',()=>{const initial=initialFormulaState();const submitted=submitFormula(initial,modified(initial),'修正',0);assert.throws(()=>reviewFormula(submitted,submitted.changes[0].id,false,'张工',''));const rejected=reviewFormula(submitted,submitted.changes[0].id,false,'张工','需重新核算');assert.equal(rejected.approved.bath,9);assert.equal(submitFormula(rejected,modified(rejected),'重新核算完成',0).changes.length,2);});
test('阻止无变化、无效输入、重复提交审核及过期版本',()=>{const initial=initialFormulaState();assert.throws(()=>submitFormula(initial,initial.approved,'原因',0));assert.throws(()=>submitFormula(initial,modified(initial),'',0));assert.throws(()=>submitFormula(initial,{...modified(initial),rows:[]},'原因',0));assert.throws(()=>submitFormula(initial,modified(initial),'原因',1));const submitted=submitFormula(initial,modified(initial),'原因',0);assert.throws(()=>submitFormula(submitted,modified(initial),'原因',0));assert.throws(()=>reviewFormula(submitted,submitted.changes[0].id,true,'',''));const approved=reviewFormula(submitted,submitted.changes[0].id,true,'张工','');assert.throws(()=>reviewFormula(approved,submitted.changes[0].id,true,'张工',''));});

test('编辑变更后配方保留原申请，审核通过采用保存值',async()=>{const {updateReviewFormula}=await import('../src/dye-formula-model.ts');const initial=initialFormulaState();const submitted=submitFormula(initial,modified(initial),'修正',0);const id=submitted.changes[0].id;const draft={...modified(initial),bath:12};const saved=updateReviewFormula(submitted,id,draft);draft.bath=15;assert.equal(saved.changes[0].after.bath,10);assert.equal(saved.changes[0].reviewedFormula.bath,12);assert.equal(saved.approved.bath,9);assert.throws(()=>updateReviewFormula(saved,id,{bath:0,rows:[]}));const approved=reviewFormula(saved,id,true,'张工','');assert.equal(approved.approved.bath,12);assert.throws(()=>updateReviewFormula(approved,id,modified(initial)));});

test('配方重打防重复，结果回写后审核生效',async()=>{const {requestFormulaRetry,completeFormulaRetry,updateReviewFormula}=await import('../src/dye-formula-model.ts');const initial=initialFormulaState();const submitted=submitFormula(initial,modified(initial),'修正',0);const id=submitted.changes[0].id;assert.throws(()=>requestFormulaRetry(submitted,id,'','原因'));const retry=requestFormulaRetry(submitted,id,'张工','核对颜色');assert.throws(()=>requestFormulaRetry(retry,id,'张工','原因'));assert.throws(()=>reviewFormula(retry,id,true,'张工',''));const adjusted=updateReviewFormula(retry,id,modified(initial));assert.deepEqual(adjusted.changes[0].reviewedFormula,modified(initial));assert.deepEqual(adjusted.changes[0].retry,retry.changes[0].retry);assert.deepEqual(adjusted.approved,initial.approved);assert.throws(()=>completeFormulaRetry(retry,id,{bath:0,rows:[]}));const completed=completeFormulaRetry(retry,id,{...modified(initial),bath:12});assert.equal(completed.approved.bath,9);assert.equal(completed.changes[0].after.bath,10);assert.ok(completed.changes[0].retry.completedAt);assert.throws(()=>completeFormulaRetry(completed,id,modified(initial)));assert.equal(reviewFormula(completed,id,true,'张工','').approved.bath,12);});

test('选择原配方或申请配方分别生效并记录处理选择',()=>{const initial=initialFormulaState();const submitted=submitFormula(initial,modified(initial),'调整',0);const id=submitted.changes[0].id;const original=reviewFormula(submitted,id,true,'水木','','original');assert.equal(original.approved.bath,9);assert.equal(original.changes[0].formulaChoice,'original');assert.equal(original.changes[0].status,'已通过');assert.throws(()=>reviewFormula(original,id,true,'水木','','requested'));const requested=reviewFormula(submitted,id,true,'水木','','requested');assert.equal(requested.approved.bath,10);assert.equal(requested.changes[0].formulaChoice,'requested');});

test('多流程卡配方和版本隔离，变更列表汇总并按卡审核',async()=>{const {loadFormulaState,saveFormulaState}=await import('../src/dye-formula-model.ts');const values=new Map();const previous=globalThis.localStorage;globalThis.localStorage={getItem:k=>values.get(k)??null,setItem:(k,v)=>values.set(k,v)};try{const a=loadFormulaState();saveFormulaState(submitFormula(a,{...a.approved,bath:11},'A变更',0));const b=loadFormulaState('Y2606303701');assert.equal(b.approved.bath,8);saveFormulaState(submitFormula(b,{...b.approved,bath:12},'B变更',0));const all=loadFormulaState();assert.equal(all.changes.length,2);const bc=all.changes.find(c=>c.card==='Y2606303701');saveFormulaState(reviewFormula(all,bc.id,true,'水木',''));assert.equal(loadFormulaState('Y2606303701').approved.bath,12);assert.equal(loadFormulaState().approved.bath,9);assert.equal(loadFormulaState().version,0);assert.equal(loadFormulaState('Y2606303701').version,1);}finally{globalThis.localStorage=previous;}});

test('排产浴比超范围申请后，确认配方用于后续排产',async()=>{const {schedulingFormula,bathFits}=await import('../src/schedule-bath.ts');const {saveFormulaState,loadFormulaState}=await import('../src/dye-formula-model.ts');const previous=globalThis.localStorage;const values=new Map();globalThis.localStorage={getItem:k=>values.get(k)??null,setItem:(k,v)=>values.set(k,v)};try{const state=schedulingFormula('Y2606305783','1:12');assert.equal(state.approved.bath,12);assert.equal(bathFits(12,'J01#'),false);assert.equal(bathFits(5,'J01#'),true);assert.equal(bathFits(9,'J01#'),true);assert.equal(bathFits(4,'J01#'),false);const next=submitFormula(state,{...state.approved,bath:9},'浴比不匹配',0,'水木');saveFormulaState(next);const all=loadFormulaState();assert.equal(all.changes[0].before.bath,12);saveFormulaState(reviewFormula(all,next.changes[0].id,true,'水木','','requested'));assert.equal(schedulingFormula('Y2606305783','1:12').approved.bath,9);}finally{globalThis.localStorage=previous;}});

test('仅按变更类型和原因提交申请，保留原配方并在审核时修改',async()=>{
 const {updateReviewFormula}=await import('../src/dye-formula-model.ts');
 for(const requestType of ['bath','auxiliary']){
  const initial=initialFormulaState();
  const submitted=submitFormula(initial,structuredClone(initial.approved),'申请调整',0,'水木',requestType);
  assert.equal(submitted.changes[0].requestType,requestType);
  assert.deepEqual(submitted.approved,initial.approved);
  assert.equal(submitted.changes[0].status,'待工段长审核');
  assert.throws(()=>submitFormula(submitted,submitted.approved,'再次申请',0,'水木',requestType));
  assert.throws(()=>submitFormula(initial,initial.approved,'',0,'水木',requestType));
  const edited=updateReviewFormula(submitted,submitted.changes[0].id,modified(initial));
  assert.equal(reviewFormula(edited,submitted.changes[0].id,true,'张工','同意').approved.bath,10);
 }
});

 test('复样进行中允许无需调整，保留原配方并结束待办',async()=>{const {requestFormulaRetry,completeFormulaRetry}=await import('../src/dye-formula-model.ts');const initial=initialFormulaState();const submitted=submitFormula(initial,modified(initial),'调整',0);const id=submitted.changes[0].id;const retry=requestFormulaRetry(submitted,id,'水木','复样');const result=reviewFormula(retry,id,true,'水木','无需调整','original');assert.deepEqual(result.approved,initial.approved);assert.equal(result.version,initial.version);assert.equal(result.changes[0].status,'已通过');assert.equal(result.changes[0].formulaChoice,'original');assert.throws(()=>completeFormulaRetry(result,id,modified(initial)));});
