import {test} from 'node:test';
import assert from 'node:assert/strict';
import {formulaNumber,formulaNumberStorage,allocateFormulaIdentity} from '../src/formula-number.ts';
import {emptyRecord,matchingFormula,matchingFormulaNumber,versionMatchingFormula,changeFormulaScope} from '../src/matching-model.ts';
import {adjustWarehouse} from '../src/warehouse-model.ts';
import {initialFormulaState,submitFormula,reviewFormula} from '../src/dye-formula-model.ts';
const base=()=>({...emptyRecord(),result:'通过',bathRatio:8,formula:structuredClone(matchingFormula)});
test('配方号使用日期和每日流水，同一配方跨日变更保持流水且持久化',()=>{const values=new Map(),previous=globalThis.localStorage;globalThis.localStorage={getItem:k=>values.get(k)??null,setItem:(k,v)=>values.set(k,v)};try{const today=new Date(2026,8,17),tomorrow=new Date(2026,8,18);assert.equal(formulaNumber(8,'card-a',0,today),'C08260917001v0');assert.equal(formulaNumber(8.5,'card-a',2,tomorrow),'C08.5260917001v2');assert.equal(formulaNumber(9,'card-b',0,today),'C09260917002v0');assert.equal(formulaNumber(6,'card-c',0,tomorrow),'C06260918001v0');assert.equal(formulaNumber(8,'card-a',0,today),'C08260917001v0');assert.equal(JSON.parse(values.get(formulaNumberStorage)).cards['card-a'].serial,1)}finally{globalThis.localStorage=previous}});
test('流水分配不覆盖既有编号，超过四位不截断',()=>{const registry={cards:{a:{date:'20260917',serial:9999}},counters:{'20260917':9999}};assert.equal(allocateFormulaIdentity(registry,'a','20260918'),registry);assert.equal(allocateFormulaIdentity(registry,'b','20260917').cards.b.serial,10000)});
test('调整浴比或比例各升级一次，确认或加料记录不改变配方版本',()=>{const a=base();const b=adjustWarehouse(a,9,a.formula,'张工','浴比调整');assert.equal(b.formulaVersion,1);assert.match(matchingFormulaNumber('Y2606305783',b),/^C09\d{9}v1$/);const c=adjustWarehouse(b,9,b.formula.map((r,i)=>i? r:{...r,ratio:2}),'张工','比例调整');assert.equal(c.formulaVersion,2);assert.equal(a.formulaVersion,undefined);assert.equal(versionMatchingFormula(c,{...c,reason:'确认完成'}).formulaVersion,2);assert.equal(versionMatchingFormula(c,{...c,additions:[{code:'CP1',amount:0.1}]}).formulaVersion,2);assert.equal(versionMatchingFormula(c,{...c,formula:c.formula.map(r=>({...r,key:'new-'+r.key}))}).formulaVersion,2)});
test('染色配方申请和退回不升级，使用原配方不升级，申请通过升级',()=>{const a=initialFormulaState(),s=submitFormula(a,{...a.approved,bath:10},'调整浴比',0),id=s.changes[0].id;assert.equal(s.version,0);assert.equal(reviewFormula(s,id,false,'张工','退回').version,0);assert.equal(reviewFormula(s,id,true,'张工','','original').version,0);assert.equal(reviewFormula(s,id,true,'张工','','requested').version,1)});

test('申请提交和编辑保留原配方号，确认后才更新浴比和版本，兼容旧待审编号',async()=>{const {changeFormulaNumber,updateReviewFormula}=await import('../src/dye-formula-model.ts');const a=initialFormulaState(),s=submitFormula(a,{...a.approved,bath:12},'浴比调整',0),c=s.changes[0];const original=formulaNumber(a.approved.bath,c.card,0);assert.equal(c.formulaNo,original);assert.equal(changeFormulaNumber({...c,formulaNo:'旧的提前升级编号'}),original);const edited=updateReviewFormula(s,c.id,{...c.after,bath:10});assert.equal(edited.changes[0].formulaNo,original);assert.equal(changeFormulaNumber(edited.changes[0]),original);const approved=reviewFormula(edited,c.id,true,'张工','','requested');assert.equal(changeFormulaNumber(approved.changes[0]),formulaNumber(10,c.card,1));assert.equal(changeFormulaNumber(reviewFormula(edited,c.id,true,'张工','','original').changes[0]),original);assert.equal(changeFormulaNumber(reviewFormula(edited,c.id,false,'张工','退回').changes[0]),original)});
