import {test} from 'node:test';
import assert from 'node:assert/strict';
import {seedWorkItems,applyWorkAction,workCounts,isRepeated,pendingCloth,teamMembers} from '../src/workbench-model.ts';
const now=Date.parse('2026-09-08T10:00:00+08:00');
test('四类待办与状态概况遵循统一统计口径',()=>{const rows=seedWorkItems(now);const c=workCounts(rows,now);assert.deepEqual([c.bulk,c.pre,c.unassigned,c.assigned,c.running,c.confirm],[7,5,8,21,10,6]);assert.equal(c.overdue,10);assert.equal(c.repeated,5);assert.equal(c.cloth,10);assert.equal(rows.filter(t=>t.phase==='已分配').length+c.running+c.confirm,c.assigned)});
test('订单审核→分配→打样→配方提交→确认形成完整闭环',()=>{let r=seedWorkItems(now)[0];r=applyWorkAction(r,{type:'approve-order'});assert.equal(r.phase,'待分配');const worker=teamMembers.find(m=>m.team===r.team).name;r=applyWorkAction(r,{type:'assign',worker});r=applyWorkAction(r,{type:'start'});r=applyWorkAction(r,{type:'submit',formula:r.formula});assert.equal(r.phase,'待确认');assert.equal(r.version,1);r=applyWorkAction(r,{type:'confirm'});assert.equal(r.phase,'已完成');assert.equal(workCounts([r],now).assigned,0);assert.equal(r.logs[0].event,'配方确认通过')});
test('错误阶段、无原因退回和跨班组分配被阻止',()=>{const r=seedWorkItems(now)[0];assert.throws(()=>applyWorkAction(r,{type:'confirm'}));assert.throws(()=>applyWorkAction(r,{type:'reject-order',reason:' '}));const pending=applyWorkAction(r,{type:'approve-order'});assert.throws(()=>applyWorkAction(pending,{type:'assign',worker:teamMembers.find(m=>m.team!==r.team).name}))});
test('配方多次退回进入异常清单且保留原因，确认后退出',()=>{let r=seedWorkItems(now)[36];r={...r,returns:1};r=applyWorkAction(r,{type:'return',reason:'色光偏红'});assert.equal(r.phase,'进行中');assert.equal(r.returns,2);assert.equal(r.lastReason,'色光偏红');assert.ok(isRepeated(r));r=applyWorkAction(r,{type:'submit',formula:r.formula});r=applyWorkAction(r,{type:'confirm'});assert.equal(isRepeated(r),false)});
test('配方确认不掩盖未完成带布，完成带布才移出清单',()=>{let r=seedWorkItems(now)[35];assert.ok(pendingCloth(r));r=applyWorkAction(r,{type:'confirm'});assert.ok(pendingCloth(r));r=applyWorkAction(r,{type:'cloth-done'});assert.equal(pendingCloth(r),false);assert.equal(r.phase,'已完成')});
test('分配会同步减少待分配并增加已分配，不虚增进行中',()=>{const rows=seedWorkItems(now),r=rows[12],before=workCounts(rows,now);const worker=teamMembers.find(m=>m.team===r.team).name;const after=workCounts(rows.map(t=>t.id===r.id?applyWorkAction(t,{type:'assign',worker}):t),now);assert.equal(after.unassigned,before.unassigned-1);assert.equal(after.assigned,before.assigned+1);assert.equal(after.running,before.running)});

test('分组柱状图的四类任务统计之和等于总览，不混入待审订单',async()=>{const {taskKindStats}=await import('../src/workbench-model.ts');const rows=seedWorkItems(now),groups=taskKindStats(rows,now),counts=workCounts(rows,now);assert.deepEqual(groups.map(g=>g.kind),['大货','回修','复样','预打样']);for(const key of ['unassigned','assigned','running','overdue'])assert.equal(groups.reduce((n,g)=>n+g[key],0),counts[key]);assert.equal(groups[0].unassigned,2);assert.equal(groups[0].bulk,7)});
test('二次加料按流程卡去重，包含2次和3次，不包含1次或无卡号任务',async()=>{const {secondAdditionCards}=await import('../src/workbench-model.ts');const rows=seedWorkItems(now),cards=secondAdditionCards(rows);assert.equal(cards.length,6);assert.ok(cards.some(r=>r.additionCount===2));assert.ok(cards.some(r=>r.additionCount===3));assert.ok(cards.every(r=>r.processCard&&r.additionCount>=2));assert.equal(secondAdditionCards([...rows,{...cards[0],id:'duplicate-task'}]).length,6)});
