import {useState} from 'react';
import {App,Button,Checkbox,DatePicker,Form,Dropdown,Empty,Input,Modal,Select,Space,Table,Tabs,Tag,Tooltip} from 'antd';
import {FileTextOutlined,SearchOutlined,FilterOutlined} from '@ant-design/icons';
import './capacity-dialog.css';
import './card-opening-review.css';
import dayjs,{type Dayjs} from 'dayjs';
import SchedulePopover,{type Allocation} from './SchedulePopover';
import {ensureScheduledDemo,type ScheduledDetail} from './capacity-demo';
import DyeFormulaTable from './DyeFormulaTable';
import OpeningProcessDetails from './OpeningProcessDetails';
import {schedulingFormula} from './schedule-bath';
import {formulaNumber} from './formula-number';
export const sales=['陆华根','朱建深','施建国','魏梦婷','郭卫刚','杜平','曾传亮','沈佩南','朱建军','王丽美','沈海军','项峰','沈亚飞','於荣伟'];
export const productionProcesses=['预定型','上油定型','退煮','酶退'] as const;
const devices=['碱退机','退煮机','平蒸机','平洗机','1#烧毛机','2#烧毛机','丝光机','冷堆机','1#定型机','2#定型机','3#定型机','4#定型机','5#定型机','6#定型机','烘干机','1#蒸蒸机','2#蒸蒸机','3#蒸蒸机','4#蒸蒸机','1#轧光机','2#轧光机','3#轧光机','4#轧光机','蒸呢机','预缩机','漂白/本白/浅色缸','中色缸','深色缸'];
const hours=[13,18,13,14,0,0,0,0,24,16,23,22,19,0,21,17,17,17,20,13,13,18,19,25,19,27,41,100];
const workInProgressHours=hours.map((hour,index)=>hour===0?0:Math.max(2,Math.round(hour*(0.28+(index%4)*0.1))));
type ColorGroup='浅'|'中'|'深'|'本白';
const colorGroups:ColorGroup[]=['浅','中','深','本白'];
// Explicit demo classifications; never infer a production color category from a color number.
const orderColorGroups:ColorGroup[]=['浅','深','中','中','深','中','浅','浅','中','浅','中','本白','浅'];
const orderColorHexes=['#a9d7bd','#263b69','#7b8593','#858a90','#35465e','#5e887c','#a8c9e5','#a8c9e5','#85898d','#b1cce5','#85898d','#f4f1e8','#a5cfa2'];
const vatColorGroups:{vat:string;group:ColorGroup}[]=Array.from({length:16},(_,i)=>({vat:`J${String(i+1).padStart(2,'0')}#`,group:i<6?'浅':i<11?'中':i<14?'深':'本白'}));
function ColorComparison({orders,scheduled,vats}:{orders:ColorGroup[];scheduled:ColorGroup[];vats:ColorGroup[]}){
 const datasets=[{key:'orders',label:'全部订单',values:orders,unit:'单'},{key:'scheduled',label:'已排订单',values:scheduled,unit:'单'},{key:'vats',label:'染缸',values:vats,unit:'台'}];
 const percent=(values:ColorGroup[],group:ColorGroup)=>values.length?values.filter(value=>value===group).length/values.length*100:0;
 return <div className="capacity-color-comparison">
  <div className="capacity-comparison-summary">
   <div className="capacity-comparison-legend">{colorGroups.map((group,index)=><span key={group}><i className={`color-group-${index}`}/>{group}</span>)}</div>
   {datasets.map(dataset=><div className="capacity-comparison-row" key={dataset.key}>
    <div className="capacity-comparison-label"><b>{dataset.label}</b><span>{dataset.values.length}{dataset.unit}</span></div>
    <div className="capacity-comparison-bar">{colorGroups.map((group,index)=>{const value=percent(dataset.values,group);return <Tooltip key={group} title={`${dataset.label} · ${group}：${dataset.values.filter(item=>item===group).length}${dataset.unit}，${value.toFixed(1)}%`}><i className={`color-group-${index}`} style={{width:`${value}%`}}>{value>=10&&<span>{Math.round(value)}%</span>}</i></Tooltip>})}</div>
   </div>)}
  </div>
  <div className="capacity-comparison-detail">
   <div className="capacity-comparison-note">以全部订单为基准，差异超过 ±5 个百分点时标红</div>
   <table><thead><tr><th>对比项</th>{colorGroups.map(group=><th key={group}>{group}</th>)}</tr></thead><tbody>{datasets.map((dataset,datasetIndex)=><tr key={dataset.key}><th>{dataset.label}</th>{colorGroups.map(group=>{const value=percent(dataset.values,group),baseline=percent(orders,group),delta=value-baseline,warn=datasetIndex>0&&Math.abs(delta)>5;return <td key={group} className={warn?'is-warning':''}><b>{Math.round(value)}%</b>{datasetIndex>0&&<span>{delta>0?'+':''}{delta.toFixed(1)}</span>}</td>})}</tr>)}</tbody></table>
  </div>
 </div>
}
function SalesComparison({orders,scheduled}:{orders:Item[];scheduled:Item[]}){
 const totalVats=orders.reduce((sum,item)=>sum+item.vats,0),scheduledVats=scheduled.reduce((sum,item)=>sum+item.vats,0);
 const names=Array.from(new Set([...orders.map(item=>item.sales),...scheduled.map(item=>item.sales)]));
 const rows=names.map(name=>{const orderCount=orders.filter(item=>item.sales===name).reduce((sum,item)=>sum+item.vats,0),scheduledCount=scheduled.filter(item=>item.sales===name).reduce((sum,item)=>sum+item.vats,0),orderPercent=totalVats?orderCount/totalVats*100:0,scheduledPercent=scheduledVats?scheduledCount/scheduledVats*100:0;return {name,orderCount,scheduledCount,orderPercent,scheduledPercent,delta:scheduledPercent-orderPercent}}).sort((a,b)=>Math.abs(b.delta)-Math.abs(a.delta)||b.orderCount-a.orderCount);
 return <div className="capacity-sales-comparison">
  <div className="capacity-sales-summary"><span><i className="is-order"/>全部订单 <b>{totalVats}</b>缸</span><span><i className="is-scheduled"/>已排订单 <b>{scheduledVats}</b>缸</span><em>按缸数占比差异排序，超过 ±5 个百分点时标红</em></div>
  <div className="capacity-sales-table"><div className="capacity-sales-table-head"><span>业务员</span><span>全部订单缸数占比</span><span>已排订单缸数占比</span><span>差异</span></div>{rows.map(row=><div className="capacity-sales-table-row" key={row.name}>
   <b>{row.name}</b>
   <div className="capacity-sales-meter"><i className="is-order" style={{width:`${row.orderPercent}%`}}/><span>{row.orderCount}缸　{row.orderPercent.toFixed(1)}%</span></div>
   <div className="capacity-sales-meter"><i className="is-scheduled" style={{width:`${row.scheduledPercent}%`}}/><span>{row.scheduledCount}缸　{row.scheduledPercent.toFixed(1)}%</span></div>
   <strong className={Math.abs(row.delta)>5?'is-warning':''}>{row.delta>0?'+':''}{row.delta.toFixed(1)}</strong>
  </div>)}</div>
 </div>
}
const baseReferenceOrders=[
 {order:'芹王AE',product:'短纤与棉',color:'薄荷绿'},
 {order:'芹王TEST',product:'短纤与棉',color:'暮蓝'},
 {order:'JS-908078',product:'阳粘纬弹',color:'1'},
 {order:'阿良剑气长城的阿良',product:'T/R',color:'测试勿动！！！！'},
 {order:'阳光1978-1',product:'T/R纬弹',color:'2#'},
 {order:'JS-908108',product:'阳粘纬弹',color:'泡泡芷青'},
 {order:'国华900-666',product:'T/R纬弹',color:'浅蓝'},
 {order:'国华900-696',product:'T/R纬弹',color:'浅蓝'},
 {order:'国华900-696',product:'T/R纬弹',color:'中灰'},
 {order:'国华900-235',product:'T/R纬弹',color:'浅兰'},
 {order:'国华900-235',product:'T/R纬弹',color:'中灰'},
 {order:'芹王AE',product:'短纤与棉',color:'石白'},
 {order:'芹王AE',product:'短纤与棉',color:'青梅绿'}
];
const referenceOrders=Array.from({length:60},(_,i)=>{
 const source=baseReferenceOrders[i%baseReferenceOrders.length];
 const batch=Math.floor(i/baseReferenceOrders.length);
 return {...source,order:batch===0?source.order:`${source.order}-${String(batch+1).padStart(2,'0')}`};
});
// Demo equipment routes list individual machines, not just process names.
const equipmentRoutes=[[0,8,25],[1,9,27],[2,8,10,26],[3,11,25],[0,12,27],[1,14,26],[2,15,25],[3,16,25],[1,17,26],[0,18,25],[2,21,26],[3,23,25],[1,24,25]];
export const items=referenceOrders.map((reference,i)=>({key:String(i),rank:i+1,vats:i<10?i+1:1,pieces:[20,28,42,16,24,18][i%6],history:i%3===1?'-':`J${String(i%16+1).padStart(2,'0')}`,linked:['ok','加料','色不准'][i%3],...reference,equipment:equipmentRoutes[i%equipmentRoutes.length],colorGroup:orderColorGroups[i%orderColorGroups.length],colorHex:orderColorHexes[i%orderColorHexes.length],head:i===0?'头缸':'连缸',created:`2026-05-${String(12-i%10).padStart(2,'0')} 21:01:14`,due:`2026-06-${String(5+i*2%24).padStart(2,'0')}`,internalDue:null as string|null,type:'正常订单',bath:i%4===1?'配方未出':i===3||i===10?'1:12':`1:${[8,9,7,9,8,9][i%6]}`,formulaStatus:i%4===1?'配方未出':i%3===0?'未确认':'已确认',processStatus:i%2===0?'已确认':'未确认',weight:[300,279,299,310,228,205][i%6]+'g',width:[1.66,1.72,1.68,1.66,1.62,1.57][i%6]+'m',sales:sales[i%sales.length],process:productionProcesses[i%productionProcesses.length],card:`Y260630${5672+i*37}`}));
export type Item=typeof items[number];
export default function CapacityDialog({open,onClose,onSchedule,onCancelSchedule,scheduledOrders,scheduledPieces,scheduledDetails}:{open:boolean;onClose:()=>void;onSchedule:(order:Item,rows:Allocation[])=>boolean;onCancelSchedule:(card:string,vat:string,slot:number)=>boolean;scheduledOrders:string[];scheduledPieces:Record<string,number>;scheduledDetails:ScheduledDetail[]}){
 const {message}=App.useApp();
 const [dueChanges,setDueChanges]=useState<Record<string,{date:string;reason:string}>>(()=>{try{return JSON.parse(localStorage.getItem('lab-capacity-internal-dates')||'{}')}catch{return {}}});
 const [editingDue,setEditingDue]=useState<Item|null>(null);
 const [dueForm]=Form.useForm();
 const editDue=(row:Item)=>{setEditingDue(row);dueForm.setFieldsValue({date:dayjs(dueChanges[row.card]?.date||row.due),reason:''})};
 const saveDue=async()=>{try{const values=await dueForm.validateFields();if(!editingDue)return;const next={...dueChanges,[editingDue.card]:{date:values.date.format('YYYY-MM-DD'),reason:values.reason.trim()}};try{localStorage.setItem('lab-capacity-internal-dates',JSON.stringify(next));setDueChanges(next);setEditingDue(null);message.success('内部交期已调整')}catch{message.error('保存失败，请检查浏览器存储后重试')}}catch{/* Form displays required field validation. */}};
 const [headOverrides,setHeadOverrides]=useState<Record<string,boolean>>(()=>{try{return JSON.parse(localStorage.getItem('lab-capacity-head-vats')||'{}')}catch{return {}}});
 const currentItems=items.map(r=>({...r,head:headOverrides[r.card]===undefined?r.head:headOverrides[r.card]?'头缸':'连缸'}));
 const salesVatCounts=Object.fromEntries(sales.map(name=>[name,currentItems.filter(item=>item.sales===name).reduce((sum,item)=>sum+item.vats,0)]));
 const orderedSales=[...sales].sort((a,b)=>salesVatCounts[b]-salesVatCounts[a]);
 const [vatKind,setVatKind]=useState('all'),[status,setStatus]=useState('available'),[view,setView]=useState('order'),[chartView,setChartView]=useState('capacity'),[showWorkInProgress,setShowWorkInProgress]=useState(false),[keyword,setKeyword]=useState(''),[color,setColor]=useState(''),[type,setType]=useState<string>(),[excluded,setExcluded]=useState<string>(),[processMode,setProcessMode]=useState<'include'|'exclude'>('exclude'),[seller,setSeller]=useState<string>(),[selected,setSelected]=useState<React.Key[]>([]),[scheduleItem,setScheduleItem]=useState<Item|null>(null),[detailItem,setDetailItem]=useState<Item|null>(null),[device,setDevice]=useState<number|null>(null),[salesDateRange,setSalesDateRange]=useState<[Dayjs,Dayjs]>(()=>{const end=dayjs('2026-05-12');return [end.subtract(6,'day'),end]});
 const demoScheduledDetails=ensureScheduledDemo(currentItems,scheduledDetails);
 const scheduled=currentItems.flatMap(r=>demoScheduledDetails.filter(j=>j.card===r.card).map((j,i)=>({...r,key:`${r.key}-${j.vat}-${j.slot}-${i}`,pieces:j.pieces??Math.max(1,Math.ceil(r.pieces/r.vats)),vats:1,productionVat:j.vat,productionSlot:j.slot}))).map((r,i)=>({...r,rank:i+1,scheduleNo:`PD${String(i+1).padStart(6,'0')}`}));
 const available=currentItems.map(r=>{const assigned=scheduled.filter(item=>item.card===r.card),usedPieces=Math.max(scheduledPieces[r.card]??0,assigned.reduce((sum,item)=>sum+item.pieces,0));return {...r,pieces:Math.max(0,r.pieces-usedPieces),vats:Math.max(0,r.vats-assigned.length)}}).filter(r=>r.pieces>0&&r.vats>0);
 const inSalesDateRange=(item:Item)=>{const date=dayjs(item.created.slice(0,10));return !date.isBefore(salesDateRange[0].startOf('day'))&&!date.isAfter(salesDateRange[1].endOf('day'))};
 const salesPeriodOrders=currentItems.filter(inSalesDateRange),salesPeriodScheduled=scheduled.filter(inSalesDateRange);
 const rows=(status==='available'?available:scheduled).filter(r=>r.order.includes(keyword)&&r.color.includes(color)&&(vatKind==='all'||r.head===vatKind)&&(!type||r.type===type)&&(!excluded||(processMode==='include'?r.process===excluded:r.process!==excluded))&&(!seller||r.sales===seller)&&(device===null||r.equipment.includes(device)));
 const chartValues=hours.map((hour,index)=>hour+(showWorkInProgress?workInProgressHours[index]:0));
 const chartMax=Math.max(100,Math.ceil(Math.max(...chartValues)/20)*20);
 const chartTicks=Array.from({length:6},(_,index)=>Math.round(chartMax*(5-index)/5));
 const cols=[{title:'序号',render:(_:unknown,__:Item,index:number)=>index+1},...(status==='scheduled'?[{title:'排产号',dataIndex:'scheduleNo'},{title:'排产缸号',dataIndex:'productionVat'}]:[{title:'可用数量',dataIndex:'pieces',render:(value:number)=>`${Math.min(100,Math.max(10,value))}匹`},{title:'剩余缸数',dataIndex:'vats',render:(value:number)=>`${value}缸`}]),{title:'订字',dataIndex:'order',render:(v:string)=><b>{v}</b>},{title:'品名',dataIndex:'product'},{title:'色号',dataIndex:'color'},{title:'颜色',dataIndex:'colorHex',render:(hex:string,r:Item)=><Tooltip title={`${r.color} · ${hex}（演示色）`}><span role="img" aria-label={`${r.color}色块`} className="capacity-order-swatch" style={{backgroundColor:hex}}/></Tooltip>},{title:'颜色深浅',dataIndex:'colorGroup',render:(v:ColorGroup)=>v==='本白'?'本白':`${v}色`},{title:<Dropdown trigger={['click']} menu={{selectable:true,selectedKeys:[vatKind],items:[{key:'all',label:'全部'},{key:'头缸',label:'头缸'},{key:'连缸',label:'连缸'}],onClick:({key})=>{setVatKind(key);setSelected([])}}}><Button type="text" className="capacity-vat-filter" aria-label="筛选头缸或连缸" style={{color:vatKind==='all'?undefined:'#1677ff'}}>头缸 <FilterOutlined/></Button></Dropdown>,dataIndex:'head',render:(v:string,r:Item)=><Checkbox aria-label={`${r.order} ${r.color} 头缸`} title="勾选为头缸，未勾选为连缸" checked={v==='头缸'} onChange={e=>{const next={...headOverrides,[r.card]:e.target.checked};setHeadOverrides(next);try{localStorage.setItem('lab-capacity-head-vats',JSON.stringify(next))}catch{/* Keep the current session usable when browser storage is unavailable. */}}}/>},{title:'浴比',dataIndex:'bath',render:(v:string)=><span style={{color:v==='配方未出'?'#ff4d4f':undefined}}>{v}</span>},{title:'配方',dataIndex:'formulaStatus',render:(v:string)=><span style={{color:v==='已确认'?'#389e0d':'#cf1322',fontWeight:600}}>{v}</span>},{title:'工艺',dataIndex:'processStatus',render:(v:string)=><span style={{color:v==='已确认'?'#389e0d':'#cf1322',fontWeight:600}}>{v}</span>},{title:'订单日期',dataIndex:'created',render:(v:string)=>v.slice(5,10)},{title:'内部交期',render:(_:unknown,r:Item)=><Button type="link" aria-label={`修改${r.order} ${r.color}内部交期`} onClick={()=>editDue(r)}>{(dueChanges[r.card]?.date||r.due).slice(5,10)}</Button>},{title:'订单类型',dataIndex:'type',render:(v:string)=><Tag color="blue">{v}</Tag>},{title:'业务员',dataIndex:'sales'},{title:'操作',render:(_:unknown,r:Item&{productionVat?:string;productionSlot?:number})=>status==='available'?<Button type="link" size="small" aria-label={`排产${r.order} ${r.color}`} onClick={event=>{event.stopPropagation();setScheduleItem(r)}}>排产</Button>:<Button danger type="link" size="small" aria-label={`取消排产${r.order} ${r.color}`} onClick={event=>{event.stopPropagation();if(r.productionVat&&r.productionSlot&&onCancelSchedule(r.card,r.productionVat,r.productionSlot))setSelected([])}}>取消排产</Button>}];
 const widths=status==='scheduled'?[4,8,8,10,8,9,4,6,6,6,6,6,8,7,6,8,7]:[4,6,6,10,8,9,4,6,6,6,6,6,8,7,6,8,6];
 const sizedColumns=cols.map((column,index)=>({...column,width:widths[index]+'%'}));
 const displayColumns=view!=='card'?sizedColumns:status==='scheduled'?sizedColumns.map((column,index)=>index===1?{...column,title:'流程卡号',dataIndex:'card'}:column):[...sizedColumns.slice(0,4),{title:'流程卡号',dataIndex:'card',width:'8%',render:(value:string)=><span>{value}</span>},...sizedColumns.slice(4)];
 const detailState=detailItem?schedulingFormula(detailItem.card,detailItem.bath):null;
 const detailVat=detailItem?(detailItem.history==='-'?'J04#':`${detailItem.history.replace(/#$/,'')}#`):'—';
 const detailDepth=detailItem?.colorGroup==='本白'?'本白':detailItem?`${detailItem.colorGroup}色`:'—';
 return <><Modal className="capacity-modal" open={open} onCancel={onClose} footer={null} width="calc(100vw - 24px)" style={{top:6}} destroyOnHidden><div className="capacity-body">
  <div className="capacity-sales">{orderedSales.map(name=><button className={seller===name?'active':''} key={name} onClick={()=>setSeller(seller===name?undefined:name)}><span>{name}</span><span>{salesVatCounts[name]} 缸</span></button>)}</div>
  <div className="capacity-order-area"><div className="capacity-filter-row"><Tabs activeKey={status} onChange={v=>{setStatus(v);setSelected([]);if(v==='available')setDevice(null)}} items={[{key:'available',label:`可排（${available.reduce((n,r)=>n+r.vats,0)}缸）`},{key:'scheduled',label:`已排（${scheduled.reduce((n,r)=>n+r.vats,0)}缸）`}]}/><div className="capacity-filter-controls">{seller&&<Tag closable onClose={()=>setSeller(undefined)}>{seller}</Tag>}<Input prefix={<SearchOutlined/>} aria-label="产能订字搜索" allowClear placeholder="请输入订字" value={keyword} onChange={e=>setKeyword(e.target.value)}/><Input prefix={<SearchOutlined/>} aria-label="产能色号搜索" allowClear placeholder="请输入色号" value={color} onChange={e=>setColor(e.target.value)}/><Select aria-label="产能订单类型" allowClear placeholder="全部订单类型" value={type} onChange={setType} options={['正常订单','厂外回修','试样布'].map(value=>({value,label:value}))}/><Space.Compact className="capacity-process-filter"><Select aria-label="工序筛选方式" value={processMode} onChange={setProcessMode} options={[{value:'include',label:'包含工序'},{value:'exclude',label:'不包含工序'}]}/><Select aria-label="选择筛选工序" allowClear placeholder="请选择工序" value={excluded} onChange={setExcluded} options={productionProcesses.map(value=>({value,label:value}))}/></Space.Compact></div></div>
  <div className="capacity-view-row"><Tabs className="capacity-view-tabs" activeKey={view} onChange={setView} items={[{key:'order',label:'订单'},{key:'card',label:'流程卡'}]}/><div className="capacity-machine-filter">{device!==null&&<Tag color="blue" closable onClose={()=>{setDevice(null);setSelected([])}}>经过设备：{devices[device]}</Tag>}</div></div><Table rowKey="key" size="small" pagination={false} tableLayout="fixed" rowSelection={{columnWidth:'2.2%',selectedRowKeys:selected,onChange:setSelected}} columns={displayColumns} dataSource={rows} scroll={{y:260}} onRow={record=>({onClick:event=>{if((event.target as HTMLElement).closest('button,a,input,.ant-checkbox,.ant-select'))return;setDetailItem(record)},style:{cursor:'pointer'},tabIndex:0,'aria-label':`查看${record.order} ${record.color}订单详情`,onKeyDown:event=>{if(event.target===event.currentTarget&&(event.key==='Enter'||event.key===' ')){event.preventDefault();setDetailItem(record)}}})} locale={{emptyText:<Empty image={Empty.PRESENTED_IMAGE_SIMPLE} description={device!==null?`当前条件下无经过${devices[device]}的已排记录`:status==='scheduled'?'暂无已排订单':'暂无符合条件的订单'}/>}}/></div>
  <div className="capacity-chart-area"><div className="capacity-chart-heading"><Tabs className="capacity-chart-tabs" activeKey={chartView} onChange={setChartView} items={[{key:'capacity',label:'工段产能'},{key:'color',label:'颜色统计'},{key:'sales',label:'业务员统计'}]}/>{chartView==='capacity'?<div className="capacity-chart-controls"><Checkbox checked={showWorkInProgress} onChange={event=>setShowWorkInProgress(event.target.checked)}>在制品</Checkbox><span className="capacity-chart-legend"><i className="is-total"/>排产时长</span>{showWorkInProgress&&<span className="capacity-chart-legend"><i className="is-wip"/>在制品时长</span>}<span>共 28 台设备</span></div>:chartView==='sales'?<div className="capacity-sales-date-filter"><span>全部订单与已排订单的业务员缸数占比对比</span><DatePicker.RangePicker aria-label="业务员统计日期范围" allowClear={false} value={salesDateRange} format="YYYY-MM-DD" onChange={values=>{if(values?.[0]&&values[1])setSalesDateRange([values[0],values[1]])}}/></div>:<span>订单、已排订单与染缸颜色结构对比</span>}</div>{chartView==='capacity'?<><div className="capacity-chart"><span className="capacity-axis-label">时长/h</span><div className="capacity-yaxis">{chartTicks.map(n=><span key={n}>{n}</span>)}</div><div className="capacity-plot"><div className="capacity-gridlines">{chartTicks.map(n=><i key={n}/>)}</div>{devices.map((name,i)=>{const combined=chartValues[i],title=showWorkInProgress?`${name}：排产 ${hours[i]} 小时 + 在制品 ${workInProgressHours[i]} 小时 = ${combined} 小时`:`${name}：排产 ${hours[i]} 小时`;return <button key={name} className={'capacity-bar-column '+(device===i?'active':'')} onClick={()=>{setDevice(device===i?null:i);setStatus('scheduled');setSelected([])}} aria-pressed={device===i} title={title} aria-label={title}><div className="capacity-bar" style={{height:`${combined/chartMax*100}%`}}>{showWorkInProgress&&combined>0&&<i className="capacity-bar-work-in-progress" style={{height:`${workInProgressHours[i]/combined*100}%`}}/>}</div><span>{name}</span></button>})}</div></div><div className="capacity-chart-caption">{device===null?'点击柱状图，查看经过该机器的已排订单或流程卡':`${devices[device]}：排产 ${hours[device]} 小时${showWorkInProgress?` + 在制品 ${workInProgressHours[device]} 小时 = ${chartValues[device]} 小时`:''} · 当前匹配 ${rows.length} 条已排记录（再次点击可清除）`} <span>本地演示数据</span></div></>:chartView==='color'?<ColorComparison orders={currentItems.map(item=>item.colorGroup)} scheduled={Array.from(new Map(scheduled.map(item=>[item.card,item.colorGroup])).values())} vats={vatColorGroups.map(vat=>vat.group)}/>:<SalesComparison orders={salesPeriodOrders} scheduled={salesPeriodScheduled}/>}</div>
 </div></Modal>{scheduleItem&&<SchedulePopover showTrigger={false} open onOpenChange={open=>{if(!open)setScheduleItem(null)}} card={scheduleItem.card} history={scheduleItem.history} order={scheduleItem.order} pieces={scheduleItem.pieces} bath={scheduleItem.bath} onSchedule={allocations=>onSchedule(scheduleItem,allocations)}/>}<Modal title="调整内部交期" open={!!editingDue} onCancel={()=>setEditingDue(null)} onOk={saveDue} okText="保存调整" cancelText="取消" destroyOnHidden>
  {editingDue&&<p>{editingDue.order} · {editingDue.color}　客户交期：{editingDue.due.slice(5,10)}</p>}
 <Form form={dueForm} layout="vertical"><Form.Item name="date" label="内部交期" rules={[{required:true,message:'请选择内部交期'}]}><DatePicker aria-label="修改内部交期" format="MM-DD" style={{width:'100%'}}/></Form.Item><Form.Item name="reason" label="调整原因" rules={[{required:true,whitespace:true,message:'请填写调整原因'}]}><Input.TextArea aria-label="内部交期调整原因" placeholder="请填写本次交期调整原因" rows={3} maxLength={300} showCount/></Form.Item></Form>
 </Modal><Modal className="capacity-detail-modal" title={detailItem?`${detailItem.order} · ${detailItem.color}`:'订单详情'} open={!!detailItem} onCancel={()=>setDetailItem(null)} footer={null} width="calc(100vw - 40px)" style={{top:12}} destroyOnHidden>
  {detailItem&&detailState&&<div className="capacity-order-detail"><dl className="opening-card-details"><div><dt>基础信息：</dt><dd>{detailItem.order} | {detailItem.product}</dd></div><div><dt>颜色信息：</dt><dd>{detailItem.color} | {detailDepth} | {detailDepth}</dd></div><div><dt>白坯信息：</dt><dd>门幅{detailItem.width} | 克重{detailItem.weight}</dd></div><div><dt>不良信息：</dt><dd>— | — | —</dd></div><div><dt>米数信息：</dt><dd>预配{detailItem.pieces}匹 | 实配未发货匹 | 实配未发货米</dd></div><div><dt>成品要求：</dt><dd>门幅无要求 | 克重无要求</dd></div><div className="opening-card-requirements"><dt>加工要求：</dt><dd>烧毛 | 轻烧毛 | 酶油 | 轧光 | 罐蒸 | 罐头 | 打长卷 | 手感按标样 | 软 | 缩水率(纬向) 1 | 六样纤维牢度 1 | 做还原清洗 | 水洗牢度(棉-级) 1 | 拉开强力(经-N) 1 | 纬斜 1 | 成品手感：滑爽 | 成品光暗：一般 | 布面起皱风格：否 | 布面光洁：否 | 高牢度：否 | 预缩要求：否</dd></div></dl><div className="opening-plan-summary"><span>预排缸号：<b>{detailVat}</b></span><span>预计进缸布重：<b>{Math.round(detailItem.pieces*15.5)} kg</b></span><span>进缸浴比：<b>{detailState.approved.bath?`1:${detailState.approved.bath}`:'—'}</b></span></div><div className="opening-review-details"><section><div className="opening-section-heading"><h3><FileTextOutlined/> 配方详情</h3>{detailItem.formulaStatus!=='已确认'&&<Tag color="red">{detailItem.formulaStatus}</Tag>}</div><div className="opening-formula-number">{formulaNumber(detailState.approved.bath,detailItem.card,detailState.version)}</div><DyeFormulaTable compact fitWidth hideProcessCode formula={detailState.approved}/></section><section><div className="opening-section-heading"><h3><FileTextOutlined/> 工艺详情</h3>{detailItem.processStatus!=='已确认'&&<Tag color="red">{detailItem.processStatus}</Tag>}</div><div className="opening-formula-number">工艺号：G{detailItem.card.replace(/\D/g,'')}v0</div><OpeningProcessDetails/></section></div></div>}
 </Modal></>
}
