import {Button,Input,InputNumber,Select,Space,Table,Tag} from 'antd';
import type {Formula,DyeRow} from './dye-formula-model';
import type {AdditionBatch} from './matching-model';
export default function DyeFormulaTable({formula,original,proposed,changedFormula,requestedFormula,confirmationFormula,showChangeConfirmation=false,additions=[],editing=false,editRatioComparison=false,ratioOnlyEditing=false,compact=false,showBath=false,hideName=false,hideProcessCode=false,fitWidth=false,ratioTitle,onChange}:{formula:Formula;original?:Formula;proposed?:Formula;changedFormula?:Formula;requestedFormula?:Formula;confirmationFormula?:Formula;showChangeConfirmation?:boolean;additions?:AdditionBatch[];editing?:boolean;editRatioComparison?:boolean;ratioOnlyEditing?:boolean;compact?:boolean;showBath?:boolean;hideName?:boolean;hideProcessCode?:boolean;fitWidth?:boolean;ratioTitle?:string;onChange?:(next:Formula)=>void}){
 const comparisonFormula=proposed??changedFormula;
 const displayRows=comparisonFormula?[...formula.rows,...comparisonFormula.rows.filter(r=>!formula.rows.some(old=>old.key===r.key))]:formula.rows;
 const patch=(key:string,value:Partial<DyeRow>)=>onChange?.({...formula,rows:formula.rows.map(r=>r.key===key?{...r,...value}:r)});
 const add=(row?:DyeRow)=>{const rows=[...formula.rows],index=row?rows.findIndex(r=>r.key===row.key)+1:rows.length;rows.splice(index,0,{key:crypto.randomUUID(),stage:row?.stage??1,code:'',name:'',ratio:0,algorithm:'布重',unit:'克/市斤',process:'',processName:'',ph:''});onChange?.({...formula,rows});};
 const input=(r:DyeRow,field:'code'|'name'|'process'|'processName'|'ph',label:string)=>editing&&!ratioOnlyEditing?<Input aria-label={`${r.key}${label}`} value={r[field]} onChange={e=>patch(r.key,{[field]:e.target.value})}/>:r[field]||'—';
 const valueOf=(row:DyeRow|undefined,field:'algorithm'|'unit')=>row?(row[field]??(field==='algorithm'?'布重':'克/市斤')):'—';
 const comparisonColumns=(field:'algorithm'|'unit',label:string)=>[
  {title:label,width:145,render:(_:unknown,r:DyeRow)=>{const before=valueOf(formula.rows.find(x=>x.key===r.key),field),after=valueOf(proposed?.rows.find(x=>x.key===r.key),field);return before===after?<span>{before}</span>:<span title="原值 / 申请变更值">{before} / <span style={{color:'#ff4d4f',fontWeight:600}}>{after}</span></span>;}}
 ];
 const additionColumns=additions.flatMap((batch,index)=>{
  const batchNumber=index+1;
  const title=<span className="dye-formula-addition-title">加料{batchNumber}比例<br/><small>({batch.mode||'正常加料'})</small>{(batch.direction||batch.depth)&&<><br/><small>{[batch.direction,batch.depth].filter(Boolean).join('；')}</small></>}</span>;
  const additionRow=(row:DyeRow)=>batch.rows?.find(item=>item.code===row.code)??(batch.code===row.code?{amount:batch.amount,process:''}:undefined);
  return [
   {title,width:125,align:'center' as const,render:(_:unknown,row:DyeRow)=>additionRow(row)?.amount??''},
   {title:`加料${batchNumber}工艺`,width:95,align:'center' as const,render:(_:unknown,row:DyeRow)=>additionRow(row)?.process??''},
  ];
 });
 return <Table<DyeRow> className="dye-formula" bordered size="small" rowKey="key" pagination={false} dataSource={displayRows} tableLayout={compact?'fixed':undefined} scroll={fitWidth?undefined:{x:compact?(editing?(editRatioComparison?1170:1050):700):proposed?(showChangeConfirmation?1420:1300):1100}} locale={{emptyText:editing&&!ratioOnlyEditing?<Button onClick={()=>add()}>新增染助剂</Button>:'暂无配方'}} columns={[
 ...(editing&&!ratioOnlyEditing?[{title:'操作',width:85,render:(_:unknown,r:DyeRow)=><Space><Button type="link" onClick={()=>add(r)}>增</Button><Button type="link" danger onClick={()=>onChange?.({...formula,rows:formula.rows.filter(x=>x.key!==r.key)})}>删</Button></Space>}]:[]),
 ...((compact||showBath)?[{title:'浴比',width:70,onCell:(_:DyeRow,index?:number)=>({rowSpan:index===0?displayRows.length:0,style:{textAlign:'center' as const,verticalAlign:'middle' as const}}),render:()=> editing&&(!ratioOnlyEditing||showBath)?<InputNumber className={original?.bath!==formula.bath?'formula-change-ratio-input':undefined} aria-label="变更后配方浴比" min={0.01} controls={false} style={{width:'100%'}} value={formula.bath} onChange={bath=>onChange?.({...formula,bath})}/>:<span>1:{formula.bath??'—'}{proposed&&formula.bath!==proposed.bath&&<><br/><span style={{color:'#ff4d4f'}}> / 1:{proposed.bath??'—'}</span></>}</span>}]:[]),
 {title:'阶段',width:65,onCell:(r:DyeRow,index?:number)=>{if(!compact||editing||index===undefined)return {};if(index>0&&displayRows[index-1].stage===r.stage)return {rowSpan:0};let end=index+1;while(end<displayRows.length&&displayRows[end].stage===r.stage)end++;return {rowSpan:end-index,style:{textAlign:'center' as const,verticalAlign:'middle' as const}};},render:(_:unknown,r:DyeRow)=>editing&&!ratioOnlyEditing?<InputNumber aria-label={`${r.key}阶段`} style={{width:'100%'}} min={1} precision={0} value={r.stage} onChange={stage=>patch(r.key,{stage:stage??0})}/>:r.stage},
 ...(!compact?[{title:'类别',width:60,render:()=> '染料'}]:[]),{title:'代码',width:110,render:(_:unknown,r:DyeRow)=><Space size={3}>{input(r,'code','代码')}{proposed&&!formula.rows.some(x=>x.key===r.key)&&<Tag color="green">新增</Tag>}{proposed&&!proposed.rows.some(x=>x.key===r.key)&&<Tag color="red">删除</Tag>}</Space>},...(!compact&&!hideName?[{title:'染助剂名称',width:140,render:(_:unknown,r:DyeRow)=>input(r,'name','名称')}]:[]),
 {title:editRatioComparison&&editing?'原比例':ratioTitle??(proposed?'原比例':'比例'),width:110,render:(_:unknown,r:DyeRow)=>requestedFormula?(requestedFormula.rows.find(row=>row.key===r.key)?.ratio??'—'):editing?(editRatioComparison?(original?.rows.find(row=>row.key===r.key)?.ratio??'—'):<InputNumber aria-label={`${r.code}比例`} min={0} style={{width:'100%'}} value={r.ratio} onChange={ratio=>patch(r.key,{ratio})}/>):proposed?(formula.rows.find(x=>x.key===r.key)?.ratio??'—'):r.ratio},
 ...(requestedFormula?[{title:'确认比例',width:120,render:(_:unknown,r:DyeRow)=>{const requested=requestedFormula.rows.find(row=>row.key===r.key)?.ratio,changed=requested!==r.ratio;return editing?<InputNumber className={changed?'formula-change-ratio-input':undefined} aria-label={`${r.code}确认比例`} min={0} style={{width:'100%'}} value={r.ratio} onChange={ratio=>patch(r.key,{ratio})}/>:<span style={{color:changed?'#ff4d4f':undefined,fontWeight:changed?600:undefined}}>{r.ratio??'—'}</span>;}}]:[]),
 ...(editing&&editRatioComparison?[{title:'变更比例',width:120,render:(_:unknown,r:DyeRow)=>{const changed=original?.rows.find(row=>row.key===r.key)?.ratio!==r.ratio;return <InputNumber className={changed?'formula-change-ratio-input':undefined} aria-label={`${r.code}变更比例`} min={0} style={{width:'100%'}} value={r.ratio} onChange={ratio=>patch(r.key,{ratio})}/>;}}]:[]),
 ...(changedFormula?[{title:'变更确认比例',width:120,render:(_:unknown,r:DyeRow)=>{const before=formula.rows.find(x=>x.key===r.key)?.ratio,next=changedFormula.rows.find(x=>x.key===r.key)?.ratio;return <span style={{color:before!==next?'#ff4d4f':undefined,fontWeight:before!==next?600:undefined}}>{next??'—'}</span>;}}]:[]),
 ...(proposed?[{title:'申请变更比例',width:120,render:(_:unknown,r:DyeRow)=>{const old=formula.rows.find(x=>x.key===r.key),next=proposed.rows.find(x=>x.key===r.key);return <span style={{color:old?.ratio!==next?.ratio?'#ff4d4f':undefined,fontWeight:old?.ratio!==next?.ratio?600:undefined}}>{next?.ratio??'—'}</span>;}}]:[]),
 ...(showChangeConfirmation?[{title:'变更确认比例',width:125,render:(_:unknown,r:DyeRow)=>{if(!confirmationFormula)return <span style={{color:'#ff4d4f',fontWeight:600}}>未确认</span>;const requested=proposed?.rows.find(row=>row.key===r.key)?.ratio,confirmed=confirmationFormula.rows.find(row=>row.key===r.key)?.ratio,changed=requested!==confirmed;return <span style={{color:changed?'#ff4d4f':undefined,fontWeight:changed?600:undefined}}>{confirmed??'—'}</span>;}}]:[]),
 ...(proposed?[...comparisonColumns('algorithm','算法'),...comparisonColumns('unit','单位')]:[
 {title:'算法',width:85,render:(_:unknown,r:DyeRow)=>editing&&!ratioOnlyEditing?<Select aria-label={`${r.code}算法`} value={r.algorithm??'布重'} style={{width:'100%'}} options={['布重','水量'].map(value=>({value,label:value}))} onChange={algorithm=>patch(r.key,{algorithm,unit:algorithm==='布重'?'克/市斤':'克/升'})}/>:r.algorithm??'布重'},
 {title:'单位',width:85,render:(_:unknown,r:DyeRow)=>r.unit??'克/市斤'}]),
 ...(!hideProcessCode?[{title:'工艺代码',width:90,render:(_:unknown,r:DyeRow)=>input(r,'process','工艺代码')}]:[]),{title:'工艺名',width:160,render:(_:unknown,r:DyeRow)=>input(r,'processName','工艺名')},{title:'pH值',width:100,render:(_:unknown,r:DyeRow)=>input(r,'ph','pH')},...additionColumns
 ].map(column=>{
 const sized=compact?{...column,width:column.title==='浴比'?42:column.title==='阶段'?38:undefined}:column;
 if(!original||editing)return sized;
 const field=({'阶段':'stage','代码':'code','申请比例':'ratio','确认比例':'ratio','比例':'ratio','算法':'algorithm','单位':'unit','工艺代码':'process','工艺名':'processName','pH值':'ph'} as Record<string,keyof DyeRow>)[String(column.title)];
 return {...sized,onCell:(row:DyeRow,index?:number)=>{const base='onCell' in column?column.onCell?.(row,index)??{}:{};const old=original.rows.find(r=>r.key===row.key),requested=requestedFormula?.rows.find(r=>r.key===row.key);const changed=column.title==='浴比'?formula.bath!==original.bath:column.title==='申请比例'&&requestedFormula?!old||requested?.ratio!==old.ratio:column.title==='确认比例'&&requestedFormula?!requested||row.ratio!==requested.ratio:field?field==='algorithm'||field==='unit'?valueOf(row,field)!==valueOf(old,field):!old||row[field]!==old[field]:false;return {...base,className:changed?'formula-changed-cell':undefined};}};
 })}/>;
}
