import {useState} from 'react';
import {App,Button,Descriptions,Drawer,Input,InputNumber,Modal,Popconfirm,Select,Space,Table,Tag,Tooltip} from 'antd';
import {DownOutlined,FileTextOutlined} from '@ant-design/icons';
import './dye-process.css';

type Step={key:string;name:string;start:number|null;target:number|null;rate:number|null;minutes:number;note:string};
type Stage={key:string;code:string;steps:Step[]};
type Process={key:string;name:string;approved:boolean;stages:Stage[]};
const templates=[{value:'0210B',label:'0210B - 漂白，直白'},{value:'0705',label:'0705 - 减量工艺'},{value:'2228',label:'2228 - 中和工艺'}];
const makeSteps=(code='0210B'):Step[]=> (code==='0210B'?[
 ['进料',null,null,null,10],['升温',45,90,3,15],['升温',90,120,3,10],['保温',120,120,null,5],['降温',120,70,3,17],['出水',null,null,null,20],['出水',null,null,null,15]
]:code==='0705'?[
 ['进料',null,null,null,10],['升温',40,95,2,28],['保温',95,95,null,30],['降温',95,60,2,18],['出水',null,null,null,10]
]:[['进料',null,null,null,8],['升温',40,60,2,10],['保温',60,60,null,15],['出水',null,null,null,10]]).map((r,i)=>({key:String(i),name:String(r[0]),start:r[1] as number|null,target:r[2] as number|null,rate:r[3] as number|null,minutes:Number(r[4]),note:''}));
const initial:Process[]=[{key:'0705',name:'0705减量',approved:true,stages:[{key:'s1',code:'0705',steps:makeSteps('0705')}]},{key:'2228',name:'2228中和',approved:false,stages:[{key:'s2',code:'2228',steps:makeSteps('2228')}]},{key:'1001',name:'1001染色',approved:false,stages:[{key:'s3',code:'0210B',steps:makeSteps()}]}];
const dyes=[{key:'1',stage:1,code:'CP1',name:'ER-1增白剂',ratio:1.455,process:'02',processName:'130°C*10′',ph:'3.4–5.6'},{key:'2',stage:1,code:'CP2',name:'增白剂CWS',ratio:0.97,process:'',processName:'',ph:''},{key:'3',stage:2,code:'B28',name:'艳蓝 KN-RHG',ratio:0.563,process:'67',processName:'60°C*50′',ph:'10.8–11.8'},{key:'4',stage:2,code:'B10',name:'3BSN红150%',ratio:0.138,process:'',processName:'',ph:''}];
const histories=[{key:'h1',order:'阳光1978-1',card:'Y2606308404',code:'0210B',name:'漂白，直白',time:'2026-09-03 15:22',worker:'沈锋'},{key:'h2',order:'芹王AE',card:'Y2606303701',code:'0705',name:'减量工艺',time:'2026-09-01 10:40',worker:'钟伟祥'},{key:'h3',order:'国张711',card:'Y2606303704',code:'2228',name:'中和工艺',time:'2026-08-30 11:41',worker:'smcs'}];
export default function DyeProcessReview({onBack}:{onBack:()=>void}){
 const {message}=App.useApp();
 const [processes,setProcesses]=useState<Process[]>(()=>{try{return JSON.parse(localStorage.getItem('lab-dye-process')||'null')||initial}catch{return initial}});
 const [current,setCurrent]=useState('1001'),[expanded,setExpanded]=useState(true),[historyOpen,setHistoryOpen]=useState(false),[historySearch,setHistorySearch]=useState(''),[historyCode,setHistoryCode]=useState('0210B'),[addOpen,setAddOpen]=useState(false),[newCode,setNewCode]=useState('0210B'),[auditOpen,setAuditOpen]=useState(false);
 const process=processes.find(p=>p.key===current)!;
 const total=process.stages.reduce((sum,s)=>sum+s.steps.reduce((n,r)=>n+r.minutes,0),0);
 const save=(next:Process[])=>{setProcesses(next);localStorage.setItem('lab-dye-process',JSON.stringify(next))};
 const updateStages=(fn:(stages:Stage[])=>Stage[])=>save(processes.map(p=>p.key===current?{...p,approved:false,stages:fn(p.stages)}:p));
 const updateStep=(stage:string,row:string,field:keyof Step,value:string|number|null)=>updateStages(stages=>stages.map(s=>s.key===stage?{...s,steps:s.steps.map(r=>r.key===row?{...r,[field]:value}:r)}:s));
 return <section className="dye-review panel">
 <div className="dye-title" onClick={()=>setExpanded(!expanded)}><h3>染色工艺审核　Y2606308404 | 阳光1978-1 | 2# | 正常转卡</h3><DownOutlined rotate={expanded?0:180}/></div>
 {expanded&&<Descriptions bordered size="small" column={6} className="dye-metadata" items={[{key:'1',label:'品名',children:<b>T/R纬弹</b>},{key:'2',label:'颜色',children:'中灰'},{key:'3',label:'浅中深',children:<b>中色</b>},{key:'4',label:'配方',children:<b>活性</b>},{key:'5',label:'预配匹米数',children:<b>5匹 / -米</b>},{key:'6',label:'实配匹米数',children:<b>10匹 / 1200米</b>}]}/>}
 <div className="dye-scroll">
 <div className="dye-process-heading"><h3>工艺-染色</h3><div className="dye-process-tabs" role="tablist" aria-label="工艺类型">{processes.map(p=><button role="tab" aria-selected={p.key===current} className={p.key===current?'active':''} key={p.key} onClick={()=>setCurrent(p.key)}>{p.name}({p.approved?'已审':'待审'})</button>)}</div><strong>总时长：{total} <span className="dye-code">|　{process.stages.map(s=>s.code).join(' / ')}</span></strong><Space className="dye-heading-actions"><Button type="primary" onClick={()=>setHistoryOpen(true)}>历史配方工艺</Button><Button type="primary" onClick={()=>setAddOpen(true)}>新增阶段</Button></Space></div>
 {process.stages.map((stage,index)=><div className="dye-stage" key={stage.key}><div className="dye-stage-heading"><Space><strong>阶段{index+1}:</strong><Select aria-label={`阶段${index+1}工艺`} value={stage.code} options={templates} style={{width:195}} onChange={code=>{Modal.confirm({title:'切换阶段工艺',content:'将使用所选工艺模板替换该阶段的步骤。',okText:'替换',cancelText:'取消',onOk:()=>updateStages(stages=>stages.map(s=>s.key===stage.key?{...s,code,steps:makeSteps(code)}:s))})}}/><Tooltip title="查看工艺模板"><Button type="text" className="blue" icon={<FileTextOutlined/>} onClick={()=>{setHistoryCode(stage.code);setHistoryOpen(true)}}/></Tooltip></Space><Popconfirm title="删除这个工艺阶段？" description="该阶段所有步骤将被删除。" onConfirm={()=>updateStages(stages=>stages.filter(s=>s.key!==stage.key))} okText="删除" cancelText="取消"><Button danger size="small">删除</Button></Popconfirm></div>
 <Table className="dye-steps" size="small" bordered pagination={false} dataSource={stage.steps} columns={[
 {title:'序号',width:70,render:(_:unknown,__:Step,i:number)=>i+1},{title:'功能名称',dataIndex:'name',width:120},
 ...([{title:'起始温度',field:'start'},{title:'目标温度',field:'target'},{title:'速率',field:'rate'}] as const).map(c=>({title:c.title,width:125,render:(_:unknown,r:Step)=><InputNumber aria-label={`阶段${index+1}第${Number(r.key)+1}步${c.title}`} controls={false} min={0} max={c.field==='rate'?20:200} value={r[c.field]} onChange={v=>updateStep(stage.key,r.key,c.field,v)}/>})),
 {title:'产量时间',width:125,render:(_:unknown,r:Step)=><InputNumber aria-label={`阶段${index+1}第${Number(r.key)+1}步时间`} min={0} max={999} value={r.minutes} onChange={v=>updateStep(stage.key,r.key,'minutes',v??0)}/>},
 {title:'说明',width:180,render:(_:unknown,r:Step)=><Input aria-label={`阶段${index+1}第${Number(r.key)+1}步说明`} value={r.note} onChange={e=>updateStep(stage.key,r.key,'note',e.target.value)}/>}
 ]} summary={()=> <Table.Summary.Row><Table.Summary.Cell index={0} colSpan={5}>工艺工时总长</Table.Summary.Cell><Table.Summary.Cell index={5}>{stage.steps.reduce((n,r)=>n+r.minutes,0)}</Table.Summary.Cell><Table.Summary.Cell index={6}/></Table.Summary.Row>}/></div>)}
 {!process.stages.length&&<div className="dye-no-stage">暂无工艺阶段，请点击“新增阶段”添加。</div>}
 <div className="dye-formula-heading"><h3>配方-染色</h3><span><span className="red">*</span>浴比：1: <InputNumber disabled value={9}/></span><Tooltip title="配方由染色配方审核页面维护"><Button disabled>新增</Button></Tooltip></div>
 <Table className="dye-formula" bordered size="small" pagination={false} dataSource={dyes} scroll={{x:1000}} columns={[{title:'阶段',dataIndex:'stage',width:48},{title:'类别',width:88,render:()=> '染料'},{title:'代码',dataIndex:'code',width:87},{title:'染助剂名称',dataIndex:'name',width:130},{title:'比例',dataIndex:'ratio',width:85},{title:'算法',width:88,render:()=> '布重'},{title:'单位',width:87,render:()=> '克/市斤'},{title:'工艺代码',dataIndex:'process',width:110},{title:'工艺名',dataIndex:'processName'},{title:'pH值',dataIndex:'ph',width:125}]}/>
 </div><div className="dye-footer">{process.approved&&<Tag color="success">{process.name}已审核</Tag>}<Button onClick={onBack}>返 回</Button><Button type="primary" disabled={process.approved||!process.stages.length} onClick={()=>setAuditOpen(true)}>审 核</Button></div>
 <Modal title="新增工艺阶段" open={addOpen} onCancel={()=>setAddOpen(false)} okText="新增" onOk={()=>{updateStages(stages=>[...stages,{key:crypto.randomUUID(),code:newCode,steps:makeSteps(newCode)}]);setAddOpen(false);message.success('已新增工艺阶段')}}><div className="dye-modal-field"><span>工艺模板</span><Select value={newCode} onChange={setNewCode} options={templates} style={{width:280}}/></div></Modal>
 <Modal title="确认工艺审核" open={auditOpen} onCancel={()=>setAuditOpen(false)} okText="审核通过" onOk={()=>{save(processes.map(p=>p.key===current?{...p,approved:true}:p));setAuditOpen(false);message.success(`${process.name}审核通过，已保存到本地`)}}><Descriptions column={1} items={[{key:1,label:'流程卡',children:'Y2606308404'},{key:2,label:'工艺',children:process.name},{key:3,label:'阶段数量',children:process.stages.length},{key:4,label:'总时长',children:`${total} 分钟`}]}/></Modal>
 <Drawer title="历史配方工艺" open={historyOpen} width={900} onClose={()=>setHistoryOpen(false)} footer={<div className="drawer-footer"><Button onClick={()=>setHistoryOpen(false)}>取消</Button><Button type="primary" onClick={()=>{updateStages(stages=>[...stages,{key:crypto.randomUUID(),code:historyCode,steps:makeSteps(historyCode)}]);setHistoryOpen(false);message.success('历史工艺已引用为新阶段')}}>引用为新阶段</Button></div>}><Input.Search placeholder="搜索订字、流程卡或工艺代码" allowClear value={historySearch} onChange={e=>setHistorySearch(e.target.value)} style={{marginBottom:16}}/><Table bordered size="small" pagination={false} rowSelection={{type:'radio',selectedRowKeys:histories.filter(h=>h.code===historyCode).map(h=>h.key),onChange:(_,rows)=>setHistoryCode(rows[0].code)}} onRow={r=>({onClick:()=>setHistoryCode(r.code)})} dataSource={histories.filter(h=>(h.order+h.card+h.code).includes(historySearch))} columns={[{title:'订字',dataIndex:'order'},{title:'流程卡',dataIndex:'card'},{title:'工艺代码',dataIndex:'code'},{title:'工艺名',dataIndex:'name'},{title:'创建时间',dataIndex:'time'}]}/><h4>工艺步骤 · {historyCode}</h4><Table bordered size="small" pagination={false} dataSource={makeSteps(historyCode)} columns={[{title:'功能名称',dataIndex:'name'},{title:'起始温度',dataIndex:'start'},{title:'目标温度',dataIndex:'target'},{title:'速率',dataIndex:'rate'},{title:'产量时间',dataIndex:'minutes'}]}/></Drawer>
 </section>
}
