import {schedulingFormula,bathFits} from './schedule-bath';
import {saveFormulaState,submitFormula} from './dye-formula-model';
import DyeFormulaTable from './DyeFormulaTable';
import {useState} from 'react';
import {App,Button,Descriptions,Drawer,Empty,Input,InputNumber,Modal,Alert,Select,Space,Tooltip} from 'antd';
import {QuestionCircleOutlined,DownOutlined} from '@ant-design/icons';
import './dye-schedule.css';
import './formula-change-review.css';
import CapacityDialog,{type Item} from './CapacityDialog';
import SchedulingDrawer from './SchedulingDrawer';
import CardOpeningReview from './CardOpeningReview';
import {type Allocation} from './SchedulePopover';
import {displayScheduleNumber,readScheduleJobs as read,vats,type Job} from './schedule-model';
const dates=['2026-09-10','2026-09-11','2026-09-12'];
export default function DyeSchedule(){
 const {message}=App.useApp();const [jobs,setJobs]=useState(read),[keyword,setKeyword]=useState(''),[depth,setDepth]=useState<string>(),[vat,setVat]=useState<string>(),[filter,setFilter]=useState({keyword:'',depth:'',vat:''}),[mode,setMode]=useState('plan'),[selected,setSelected]=useState<string[]>([]),[detail,setDetail]=useState<Job|null>(null),[stats,setStats]=useState(false),[planning,setPlanning]=useState(false);
 const [bathDetailsOpen,setBathDetailsOpen]=useState(true);
 const [bathRequest,setBathRequest]=useState<{item:Item;allocations:Allocation[]}|null>(null),[newBath,setNewBath]=useState<number|null>(9),[bathReason,setBathReason]=useState('');
 const requestFormula=bathRequest?schedulingFormula(bathRequest.item.card,bathRequest.item.bath):null;
 const submitBath=()=>{if(!bathRequest)return;try{const current=schedulingFormula(bathRequest.item.card,bathRequest.item.bath);if(!newBath||bathRequest.allocations.some(a=>!bathFits(newBath,a.vat))){message.warning('申请浴比必须在所选染缸范围内');return;}const next=submitFormula(current,{...current.approved,bath:newBath},bathReason,current.version,'水木');next.changes[0]={...next.changes[0],order:bathRequest.item.order,colorNo:bathRequest.item.color,source:'染缸排产'};saveFormulaState(next);setBathRequest(null);message.success('浴比变更已发起，请到配方变更确认后重新排产');}catch(e){message.error((e as Error).message)}};
 const visible=jobs.filter(j=>(!filter.keyword||`${j.card}${j.order}${j.color}`.includes(filter.keyword))&&(!filter.depth||j.depth===filter.depth)&&(!filter.vat||j.vat===filter.vat)&&(mode==='plan'||j.state==='running'||j.state==='ready'));
 const visibleVats=vats.filter(v=>(!filter.vat||v===filter.vat)&&(!filter.keyword&&!filter.depth||visible.some(j=>j.vat===v)));
 const persist=(next:Job[])=>{try{localStorage.setItem('lab-dye-schedule',JSON.stringify(next));setJobs(next);return true}catch{message.error('保存失败，请检查浏览器存储空间');return false}};
 const schedule=(item:Item,allocations:Allocation[])=>{const state=schedulingFormula(item.card,item.bath);if(state.changes.some(c=>c.card===item.card&&c.status==='待工段长审核')){message.warning('该流程卡有配方变更待确认，请先完成确认');return false;}if(!state.approved.bath){message.warning('配方未出，暂不能排产');return false;}if(allocations.some(a=>!bathFits(state.approved.bath!,a.vat))){setBathRequest({item,allocations:structuredClone(allocations)});setBathDetailsOpen(true);setNewBath(9);setBathReason('配方浴比超出染缸浴比范围');return true;}if(allocations.some(a=>jobs.some(j=>j.vat===a.vat&&j.slot===a.slot-1))){message.warning('所选排缸位置已有任务，请选择空闲位置');return false;}
 const added:Job[]=allocations.map(a=>({id:crypto.randomUUID(),vat:a.vat,slot:a.slot-1,card:item.card,order:item.order,color:item.color,depth:item.colorGroup==='本白'?'本白':`${item.colorGroup}色`,hex:item.colorHex,state:'planned',next:'染色',hours:(a.slot-1)*6,urgent:false,pieces:a.pieces!}));if(persist([...jobs,...added])){message.success('排产已保存');return true;}return false;};
 const cancelSchedule=(card:string,vatName:string,slot:number)=>{const target=jobs.find(job=>job.card===card&&job.vat===vatName&&job.slot===slot-1);if(!target){message.warning('未找到对应排产记录，请刷新后重试');return false;}if(!persist(jobs.filter(job=>job.id!==target.id)))return false;setSelected(current=>current.filter(id=>id!==target.id));if(detail?.id===target.id)setDetail(null);message.success('已取消排产');return true;};
 return <div className="dye-schedule">
  <div className="schedule-toolbar"><Input aria-label="排产搜索" placeholder="请搜索订字/色号" value={keyword} onChange={e=>setKeyword(e.target.value)} onPressEnter={()=>setFilter({keyword,depth:depth||'',vat:vat||''})} style={{width:165}}/><Select aria-label="深浅色筛选" placeholder="深浅色：请选择" allowClear value={depth} onChange={setDepth} options={['浅色','中色','深色'].map(value=>({value,label:value}))} style={{width:150}}/><Select aria-label="染缸筛选" placeholder="缸号：请选择" allowClear value={vat} onChange={setVat} options={vats.map(value=>({value,label:value}))} style={{width:140}}/><Button type="primary" onClick={()=>setFilter({keyword,depth:depth||'',vat:vat||''})}>查询</Button><Button onClick={()=>{setKeyword('');setDepth(undefined);setVat(undefined);setFilter({keyword:'',depth:'',vat:''})}}>重置</Button><Space.Compact><Button type={mode==='plan'?'primary':'default'} ghost={mode==='plan'} onClick={()=>setMode('plan')}>染缸排产</Button><Button type={mode==='live'?'primary':'default'} ghost={mode==='live'} onClick={()=>setMode('live')}>实时排产</Button></Space.Compact><span className="schedule-spacer"/><Button type="primary" onClick={()=>setStats(true)}>排产新</Button><Button type="primary" disabled={!selected.length} onClick={()=>{if(persist(jobs.map(j=>selected.includes(j.id)?{...j,converted:true}:j))){message.success(`已为 ${selected.length} 项任务转卡`);setSelected([])}}}>批量转卡</Button><Button type="primary" disabled={!selected.length} onClick={()=>window.print()}>批量打印</Button><Button type="primary" onClick={()=>setPlanning(true)}>排产</Button><Button onClick={()=>{setJobs(read());setSelected([]);message.success('排产数据已刷新')}}>刷新数据</Button></div>
  <div className="schedule-legend"><span>演示排产 · 点击卡片查看，勾选后批量操作</span><span className="schedule-spacer"/>{[['running','生产中 / 超时'],['ready','准备进缸'],['planned','计划进缸'],['waiting','后续待排']].map(([c,t])=><span key={c}><i className={c}/>{t}</span>)}{selected.length>0&&<a onClick={()=>setSelected([])}>已选 {selected.length} 项 · 清空</a>}</div>
  <div className="schedule-board"><div className="schedule-grid">
   <div className="schedule-grid-head"><div className="schedule-vat-title">染缸 <Tooltip title="每行对应一台染缸，卡片按计划顺序展示"><QuestionCircleOutlined/></Tooltip></div><div style={{gridColumn:'span 2'}}>{dates[0]}</div><div style={{gridColumn:'span 3'}}>{dates[1]}</div><div style={{gridColumn:'span 3'}}>{dates[2]}</div></div>
   {visibleVats.map(v=><div className="schedule-grid-row" key={v}><button className="schedule-vat" onClick={()=>{setVat(v);setFilter({...filter,vat:v})}}>{v}</button>{Array.from({length:8},(_,slot)=>{const job=visible.find(j=>j.vat===v&&j.slot===slot),displayNo=job?displayScheduleNumber(job):'';return <div className={'schedule-slot '+(slot===1||slot===4?'day-end':'')} key={slot}>{job&&<div role="button" tabIndex={0} aria-label={job.state==='waiting'?`查看排产计划 ${displayNo} ${v}`:`查看流程卡 ${displayNo} ${v}`} onKeyDown={e=>{if(e.key==='Enter')setDetail(job)}} onClick={()=>setDetail(job)} className={`schedule-job ${job.state}${job.urgent?' urgent':''}${selected.includes(job.id)?' checked':''}${selected.length&&!selected.includes(job.id)?' print-hide':''}`}><div className="schedule-swatch"><i style={{background:job.hex}}/>{job.depth}</div><div className="schedule-job-text"><b>{displayNo}</b> | {job.order} | {job.color}<div>{job.state==='running'?`开始：09-03 ${10+vats.indexOf(v)%7}:24 | 超时:6.${vats.indexOf(v)%9}天`:job.state==='ready'?'准备进缸 | 下道：'+job.next:`${job.hours}时后进缸 | 下道：${job.next}`}</div>{job.state!=='running'&&<div>减量 中和 染色 {job.converted?'· 已转卡':''}</div>}</div><input aria-label={`选择 ${displayNo} ${v}`} type="checkbox" checked={selected.includes(job.id)} onClick={e=>e.stopPropagation()} onChange={e=>setSelected(s=>e.target.checked?[...s,job.id]:s.filter(id=>id!==job.id))}/><span className="schedule-sequence">{String(slot+1).padStart(2,'0')}</span></div>}</div>})}</div>)}
   {!visibleVats.length&&<Empty description="未找到符合条件的排产任务"/>}
  </div></div>
  <Drawer title="排产任务详情" open={!!detail&&detail.state!=='waiting'} onClose={()=>setDetail(null)} width={550}>{detail&&<Descriptions bordered column={1} items={Object.entries({[detail.state==='waiting'?'排产号':'流程卡']:displayScheduleNumber(detail),'染缸':detail.vat,'订字':detail.order||'未填写','色号':detail.color||'未填写','颜色深浅':detail.depth||'未记录','计划日期':dates[detail.slot<2?0:detail.slot<5?1:2],'排产顺序':detail.slot+1,'下道工序':detail.next,'转卡状态':jobs.find(j=>j.id===detail.id)?.converted?'已转卡':'未转卡'}).map(([label,children])=>({key:label,label,children}))}/>}</Drawer>
  <CapacityDialog scheduledDetails={jobs.map(j=>({card:j.card,vat:j.vat,slot:j.slot+1,pieces:j.pieces}))} scheduledPieces={jobs.reduce<Record<string,number>>((acc,j)=>{if(j.pieces!==undefined)acc[j.card]=(acc[j.card]||0)+j.pieces;return acc},{})} scheduledOrders={jobs.map(j=>j.card)} open={stats} onClose={()=>setStats(false)} onSchedule={schedule} onCancelSchedule={cancelSchedule}/>
  <Modal title="发起浴比变更" open={!!bathRequest} onCancel={()=>setBathRequest(null)} onOk={submitBath} width={1100} okText="提交浴比变更" cancelText="取消" okButtonProps={{disabled:!bathReason.trim()}}>{bathRequest&&requestFormula&&<><Alert type="warning" showIcon message="配方浴比超出染缸范围，请先申请浴比变更，确认后重新排产。"/><div className="formula-card-heading" style={{marginTop:12}}><h3>流程卡详情</h3><Button type="text" aria-label={bathDetailsOpen?'收起流程卡详情':'展开流程卡详情'} icon={<DownOutlined rotate={bathDetailsOpen?180:0}/>} onClick={()=>setBathDetailsOpen(!bathDetailsOpen)}/></div>{bathDetailsOpen&&<Descriptions className="formula-card-metadata" bordered size="small" column={3} items={[
 {key:'basic',label:'基础信息',children:`${bathRequest.item.card} | ${bathRequest.item.order} | ${bathRequest.item.product}`},
 {key:'color',label:'颜色信息',children:`${bathRequest.item.color} | ${bathRequest.item.colorGroup==='本白'?'本白':bathRequest.item.colorGroup+'色'}`},
 {key:'fabric',label:'白坯信息',children:`门幅${bathRequest.item.width} | 克重${bathRequest.item.weight}`},
 {key:'defect',label:'不良信息',children:'—'},
 {key:'quantity',label:'米数信息',children:`预配${bathRequest.allocations.reduce((sum,row)=>sum+(row.pieces??0),0)}匹 | 实配匹数未记录 | 实配米数未记录`},
 {key:'finished',label:'成品要求',children:'—'},
 {key:'requirements',label:'加工要求',children:'无要求',span:3}
 ]}/>}<h3>配方详情</h3><DyeFormulaTable compact formula={requestFormula.approved}/><Space style={{marginTop:16}}>申请浴比：1:<InputNumber aria-label="申请浴比" min={5} max={9} value={newBath} onChange={setNewBath}/></Space><Input.TextArea aria-label="浴比变更原因" style={{marginTop:12}} rows={2} placeholder="变更原因（必填）" value={bathReason} onChange={e=>setBathReason(e.target.value)}/></>}</Modal>
  <Modal title="开卡审核" open={!!detail&&detail.state==='waiting'} width="94vw" style={{top:20}} footer={null} destroyOnClose onCancel={()=>setDetail(null)}>
   {detail?.state==='waiting'&&<CardOpeningReview key={detail.id} planId={detail.id} onWarehouse={()=>message.info('请到进仓确认页面处理')} onApproved={()=>{setJobs(read());setDetail(null)}}/>}
  </Modal>
  <SchedulingDrawer open={planning} onClose={()=>setPlanning(false)} jobs={jobs} onSchedule={schedule}/>

 </div>
}
