export type Job={id:string;vat:string;slot:number;card:string;order:string;color:string;depth:string;hex:string;state:'running'|'ready'|'planned'|'waiting';next:string;hours:number;urgent:boolean;pieces?:number;entryWeight?:string|number;head?:string;converted?:boolean;completed?:boolean;currentProcess?:string};
export const vats=Array.from({length:16},(_,i)=>`J${String(i+1).padStart(2,'0')}#`);
const names=['芹王AE','芹王TEST','项阳CVC2602','阳光1978-1','如华12362A','国华900-6','明帅24021','隆BS精1','统帛411','平月230'];
const colors=['白银','紫灰','薄荷绿','驼色','中灰','浅蓝','灰色','深蓝'];
const seed:Job[]=vats.flatMap((vat,i)=>Array.from({length:i===0?8:i%5===0?5:3+i%2},(_,slot)=>({id:`${vat}-${slot}`,vat,slot,card:slot===0?['Y2608307405','Y2609010017','Y2609017005','Y2608300301'][i%4]:`Y260630${String(2108+i*113+slot*37).padStart(4,'0')}${slot===1?'-1':''}`,order:slot===0?'':names[(i+slot-1)%names.length],color:slot===0?'':colors[(i+slot-1)%colors.length],depth:slot===0?'':slot%3===0?'深色':i%3===0?'浅色':'中色',hex:slot===0?'#515962':['#f4ffff','#c55078','#98bf92','#434b4d','#051927','#24316f'][(i+slot-1)%6],state:slot===0?'running':slot===1||i>1&&slot<4?'ready':slot>5?'waiting':'planned',next:i%3===0?'减量':i%3===1?'中和':'白坯发货',hours:slot*6-6,urgent:slot===1&&i===7||slot===2&&i===8})));
// Planned demo orders share process-card identifiers with the capacity order list.
const plannedDemo=Array.from({length:6},(_,i):Job=>{const index=i===0?0:i<3?1:2;return {id:`capacity-demo-${i}`,vat:vats[i+1],slot:5,card:`Y260630${5672+index*37}`,order:['芹王AE','芹王TEST','JS-908078'][index],color:['薄荷绿','暮蓝','1'][index],depth:['浅色','深色','中色'][index],hex:['#a9d7bd','#263b69','#7b8593'][index],state:'planned',next:'染色',hours:24,urgent:false,pieces:index===0?20:14};});
export const readScheduleJobs=():Job[]=>{let result:Job[];try{const x=JSON.parse(localStorage.getItem('lab-dye-schedule')||'null');result=Array.isArray(x)?[...x]:[...seed]}catch{result=[...seed]}
 const existingCards=new Set(result.map(j=>j.card));
 for(const demo of plannedDemo){if(existingCards.has(demo.card))continue;let target={vat:demo.vat,slot:demo.slot};if(result.some(j=>j.vat===target.vat&&j.slot===target.slot)){const free=vats.flatMap(vat=>Array.from({length:8},(_,slot)=>({vat,slot}))).find(t=>!result.some(j=>j.vat===t.vat&&j.slot===t.slot));if(!free)continue;target=free;}result.push({...demo,...target});}return result;};
