import {useEffect,useMemo,useState} from 'react';
import {Button,Empty,Select,Space,Tooltip} from 'antd';
import {ArrowRightOutlined,CheckCircleOutlined,ClockCircleOutlined,ExperimentOutlined,FileDoneOutlined,InfoCircleOutlined,ReloadOutlined,TeamOutlined,UndoOutlined,WarningOutlined} from '@ant-design/icons';
import dayjs from 'dayjs';
import {isOverdue,isRepeated,pendingCloth,readWorkbenchItems,secondAdditionCards,taskKindStats,workCounts,type WorkItem} from './workbench-model';
import type {Queue,Risk,WorkbenchTarget} from './workbench-navigation';
import './workbench-overview.css';
const series=[{key:'unassigned',label:'待分配',color:'#eeb762',queue:'assign'},{key:'assigned',label:'已分配',color:'#6d9ee8',queue:'assigned'},{key:'running',label:'进行中',color:'#65b6a6',queue:'running'},{key:'overdue',label:'超时',color:'#e98487',queue:'all'}] as const;
const formatter=(date:string)=>dayjs(date).format('MM-DD HH:mm');
export default function Workbench({onNavigate}:{onNavigate:(target:WorkbenchTarget)=>void}){
 const [items,setItems]=useState(readWorkbenchItems),[team,setTeam]=useState('全部班组'),[now,setNow]=useState(Date.now());
 useEffect(()=>{const timer=setInterval(()=>setNow(Date.now()),60000);const sync=()=>{setItems(readWorkbenchItems());setNow(Date.now())};window.addEventListener('storage',sync);return ()=>{clearInterval(timer);window.removeEventListener('storage',sync)}},[]);
 const scope=useMemo(()=>items.filter(r=>team==='全部班组'||r.team===team),[items,team]);
 const counts=workCounts(scope,now),groups=taskKindStats(scope,now);
 const go=(target:WorkbenchTarget)=>onNavigate({...target,team});
 const gotoQueue=(queue:Queue,kind?:WorkItem['kind'])=>go({page:queue==='assign'?'任务分配':'试样任务跟踪',queue,kind});
 const gotoRisk=(risk:Risk,id?:string,kind?:WorkItem['kind'])=>go({page:risk==='cloth'?'带布跟进':risk==='addition'?'加料流程卡':'试样任务跟踪',queue:'all',risk,id,kind});
 const overdue=scope.filter(r=>isOverdue(r,now)).sort((a,b)=>+new Date(a.due)-+new Date(b.due));
 const repeated=scope.filter(isRepeated).sort((a,b)=>b.returns-a.returns);
 const additions=secondAdditionCards(scope).sort((a,b)=>(b.additionCount??0)-(a.additionCount??0));
 const cloth=scope.filter(pendingCloth).sort((a,b)=>+new Date(a.clothDue)-+new Date(b.clothDue));
 const tasks=[{key:'bulk',title:'大货订单审核',count:counts.bulk,note:'大货订单待审核',icon:<FileDoneOutlined/>,accent:'blue',page:'大货订单审核'},{key:'pre',title:'预打样订单审核',count:counts.pre,note:'预打样订单待审核',icon:<ExperimentOutlined/>,accent:'purple',page:'预打样订单审核'},{key:'assign',title:'任务分配',count:counts.unassigned,note:'已审核，等待分配打样员',icon:<TeamOutlined/>,accent:'gold',page:'任务分配'},{key:'confirm',title:'配方确认',count:counts.confirm,note:'打样员已提交，等待确认',icon:<CheckCircleOutlined/>,accent:'green',page:'配方确认'}] as const;
 const plot={left:45,right:860,top:28,bottom:274},highest=Math.max(4,...groups.flatMap(g=>series.map(s=>g[s.key]))),step=Math.max(1,Math.ceil(highest/4)),ceiling=step*4;
 const y=(value:number)=>plot.bottom-value/ceiling*(plot.bottom-plot.top);
 const riskSections=[{key:'overdue' as Risk,title:'超时任务',count:counts.overdue,icon:<ClockCircleOutlined/>,rows:overdue,empty:'当前没有超时任务',note:(r:WorkItem)=>`要求交期 ${formatter(r.due)}`,badge:(r:WorkItem)=>`${Math.max(1,Math.ceil((now-+new Date(r.due))/3600000))}h`},{key:'repeated' as Risk,title:'多次退回',count:counts.repeated,icon:<UndoOutlined/>,rows:repeated,empty:'当前没有多次退回任务',note:(r:WorkItem)=>r.lastReason,badge:(r:WorkItem)=>`${r.returns} 次`},{key:'cloth' as Risk,title:'带布未完成',count:counts.cloth,icon:<ExperimentOutlined/>,rows:cloth,empty:'当前没有待跟进的带布任务',note:(r:WorkItem)=>`${r.cloth} · 负责人 ${r.clothOwner}`,badge:(r:WorkItem)=>r.cloth},{key:'addition' as Risk,title:'二次加料流程卡',count:additions.length,icon:<ExperimentOutlined/>,rows:additions,empty:'暂无二次加料流程卡',note:(r:WorkItem)=>`${r.order} · ${r.worker||r.team}`,badge:(r:WorkItem)=>`${r.additionCount} 次`}];
 return <div className="workbench-overview">
 <div className="overview-heading"><div><h1>试样管理工作台</h1><span>待办提醒与任务概况</span></div><Space size={10}><span className="overview-date">{dayjs(now).format('YYYY年MM月DD日')}</span><Select aria-label="工作台班组" value={team} style={{width:112}} options={['全部班组','甲班','乙班','丙班'].map(value=>({value,label:value}))} onChange={setTeam}/><Tooltip title="刷新统计"><Button aria-label="刷新统计" icon={<ReloadOutlined/>} onClick={()=>{setItems(readWorkbenchItems());setNow(Date.now())}}/></Tooltip></Space></div>
 <div className="overview-todos">{tasks.map(t=><button className={`overview-todo ${t.accent}`} key={t.key} aria-label={`${t.title} ${t.count} 项，前往处理`} onClick={()=>go({page:t.page,queue:t.key})}><div className="overview-todo-icon">{t.icon}</div><div className="overview-todo-copy"><strong>{t.title}</strong><small>{t.note}</small></div><b>{t.count}<small>项</small></b><ArrowRightOutlined className="overview-todo-arrow"/></button>)}</div>
 <div className="overview-content"><section className="overview-chart-panel"><div className="overview-section-heading"><div><h2>任务统计</h2><span>按任务类型查看当前进展</span></div><Button type="link" onClick={()=>go({page:'试样任务跟踪',queue:'all'})}>查看全部任务 <ArrowRightOutlined/></Button></div>
 <div className="overview-stat-totals">{series.map(s=><button key={s.key} onClick={()=>s.key==='overdue'?gotoRisk('overdue'):gotoQueue(s.queue)} aria-label={`${s.label} ${counts[s.key]} 项，查看任务`}><span><i style={{background:s.color}}/>{s.label}</span><strong style={{color:s.key==='overdue'?'#d97079':undefined}}>{counts[s.key]}<small>项</small></strong></button>)}</div>
 <div className="overview-chart-title"><span>任务数量 / 项</span><div className="overview-legend">{series.map(s=><span key={s.key}><i style={{background:s.color}}/>{s.label}</span>)}</div></div>
 <div className="overview-chart" data-testid="task-kind-chart"><svg viewBox="0 0 900 322" preserveAspectRatio="none" role="group" aria-label="四类任务分组柱状图"><title>大货、回修、复样、预打样的待分配、已分配、进行中和超时数量</title>{Array.from({length:5},(_,i)=>i*step).map(value=><g key={value}><line x1={plot.left} x2={plot.right} y1={y(value)} y2={y(value)} stroke="#eaf0f6" strokeDasharray={value?'4 5':undefined}/><text x={plot.left-13} y={y(value)+4} textAnchor="end" fill="#a2adbb" fontSize={12}>{value}</text></g>)}{groups.map((g,i)=>{const center=plot.left+(i+.5)*(plot.right-plot.left)/4;return <g key={g.kind}>{series.map((s,j)=>{const value=g[s.key],x=center-63+j*33,top=y(value);return <g key={s.key} role="button" tabIndex={0} aria-label={`${g.kind} ${s.label} ${value} 项，查看任务`} className="overview-bar" onClick={()=>s.key==='overdue'?gotoRisk('overdue',undefined,g.kind):gotoQueue(s.queue,g.kind)} onKeyDown={e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();s.key==='overdue'?gotoRisk('overdue',undefined,g.kind):gotoQueue(s.queue,g.kind)}}}><title>{g.kind} · {s.label}：{value} 项，点击查看任务</title><rect x={x-3} y={Math.min(top-21,plot.bottom-22)} width={31} height={Math.max(22,plot.bottom-top+21)} fill="transparent"/><rect x={x} y={value?top:plot.bottom-2} width={24} height={value?plot.bottom-top:2} rx={3} fill={s.color} opacity={value?1:.3}/><text x={x+12} y={top-8} textAnchor="middle" fill={value?'#68788e':'#b6c0cc'} fontSize={12}>{value}</text></g>})}<text x={center} y={306} textAnchor="middle" fill="#576a84" fontWeight="500" fontSize={14}>{g.kind}</text></g>})}</svg></div>
 <div className="overview-chart-foot"><InfoCircleOutlined/><span>已分配含进行中、待确认；超时与状态交叉统计。点击柱子查看对应任务。</span></div></section>
 <aside className="overview-risk-panel"><div className="overview-section-heading"><div><h2><WarningOutlined/> 异常提醒</h2></div><span>优先关注</span></div>{riskSections.map(s=><section className={`overview-risk-section ${s.key}`} key={s.key}><button className="overview-risk-heading" onClick={()=>gotoRisk(s.key)} aria-label={`${s.title} ${s.count} 项，查看全部`}><span>{s.icon} {s.title}<b>{s.count}</b></span><small>查看全部 <ArrowRightOutlined/></small></button><div className="overview-risk-list">{s.rows.length?s.rows.slice(0,2).map(r=><button key={r.id} className="overview-risk-item" onClick={()=>gotoRisk(s.key,r.id)}><span><strong>{s.key==='addition'?r.processCard:r.order}</strong><em>{s.badge(r)}</em></span><small title={`${r.colorNo} · ${r.worker||r.team} · ${s.note(r)}`}>{s.key==='addition'?`${r.order} · ${r.worker||r.team}`:`${r.colorNo} · ${r.worker||r.team} · ${s.note(r)}`}</small></button>):<div className="overview-risk-empty"><CheckCircleOutlined/> {s.empty}</div>}</div><span className="overview-risk-rule">{s.key==='overdue'?'交期已过且任务未完成':s.key==='repeated'?'累计退回 ≥ 2 次且未完成':s.key==='cloth'?'包括待带布和带布中的任务':'累计加料 ≥ 2 次，按流程卡去重'}</span></section>)}</aside></div>
 <footer className="overview-footer"><span><i/> 统计范围：{team} · 当前任务</span><span>数据更新于 {dayjs(now).format('HH:mm')} · 本地演示数据</span></footer>
 </div>
}
